# Generated by Django 4.1.2 on 2023-04-26 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_ID', models.CharField(default=uuid.uuid4, editable=False, max_length=32)),
                ('download_link', models.URLField(default='None', editable=False, max_length=400)),
            ],
        ),
    ]
