# Generated by Django 4.1.2 on 2023-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('user', models.CharField(default='Anonymous', max_length=200)),
            ],
            options={
                'db_table': 'access_logs',
            },
        ),
    ]
