# Generated by Django 4.1.2 on 2023-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_logging', '0002_accesslog_isp_accesslog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='params',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
