# Generated by Django 4.1.2 on 2022-12-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
