# Generated by Django 4.2.5 on 2023-09-30 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_ID',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32),
        ),
    ]
